Working With date and time

In [1]:
import pandas as pd
import numpy as np

In [2]:
date=pd.read_csv('orders.csv')
time=pd.read_csv('messages.csv')

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [13]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [14]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [15]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

        Working With dates

In [17]:
#converting to datetime datatype
date['date']=pd.to_datetime(date['date'])
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [26]:
#Extract year from datetime
date['date_year']=date['date'].dt.year
date.sample(5)

          date  product_id  city_id  orders  date_month  date_year
805 2019-11-28        6339       26       7          11       2019
542 2019-06-10        2652       18      69           6       2019
246 2019-12-10        2253       13      46          12       2019
490 2019-06-21        2254       16       4           6       2019
939 2018-08-07        5278       13       1           8       2018

In [27]:
# Extract month from date time
date['date_month']=date['date'].dt.month
date.sample(5)

          date  product_id  city_id  orders  date_month  date_year
36  2018-07-13        3432       13      28           7       2018
293 2018-09-12        3151       26       1           9       2018
574 2019-11-13        5639       25       4          11       2019
2   2018-10-23        1859       25       1          10       2018
130 2019-07-12        2242        8       2           7       2019

In [32]:
#extract month name
date['date_month_name']=date['date'].dt.month_name()
date.sample(5)

,date,product_id,city_id,orders,date_month,date_year,date_month_name
32,2018-10-23,2845,23,1,10,2018,October
959,2018-12-07,1700,8,2,12,2018,December
737,2019-04-24,668,2,3,4,2019,April
374,2018-12-16,4595,13,1,12,2018,December
818,2018-11-06,6941,30,9,11,2018,November

In [36]:
#Extract day
date['date_day']=date['date'].dt.day
date.sample(5)

,date,product_id,city_id,orders,date_month,date_year,date_month_name,date_day,date_dow
707,2019-07-06,2247,16,9,7,2019,July,6,5
966,2019-11-17,5975,18,1,11,2019,November,17,6
84,2018-07-30,7350,16,76,7,2018,July,30,0
777,2018-12-23,3833,26,212,12,2018,December,23,6
875,2018-11-01,4495,28,1,11,2018,November,1,3

In [37]:
#day of week
date['date_dow']=date['date'].dt.day_of_week
date.sample(5)

,date,product_id,city_id,orders,date_month,date_year,date_month_name,date_day,date_dow
300,2019-05-31,2981,26,1004,5,2019,May,31,4
15,2019-02-14,202,2,4,2,2019,February,14,3
711,2019-07-13,6201,0,3,7,2019,July,13,5
190,2019-07-13,776,13,2,7,2019,July,13,5
149,2019-02-09,1024,10,2,2,2019,February,9,5

In [39]:
#day of week -name
date['date_day_name']=date['date'].dt.day_name()
date.sample(5)

,date,product_id,city_id,orders,date_month,date_year,date_month_name,date_day,date_dow,date_day_name
858,2019-07-13,2465,29,1,7,2019,July,13,5,Saturday
123,2019-07-19,959,16,16,7,2019,July,19,4,Friday
611,2019-01-30,1284,17,11,1,2019,January,30,2,Wednesday
90,2019-12-16,7491,13,1,12,2019,December,16,0,Monday
591,2019-10-15,5386,25,2,10,2019,October,15,1,Tuesday

In [41]:
#is weekend????
date['date_is_weekend']=np.where(date['date_day_name'].isin(['Sunday','Saturday']),1,0)
date.head()

,date,product_id,city_id,orders,date_month,date_year,date_month_name,date_day,date_dow,date_day_name,date_is_weekend
0,2019-12-10,5628,25,3,12,2019,December,10,1,Tuesday,0
1,2018-08-15,3646,14,157,8,2018,August,15,2,Wednesday,0
2,2018-10-23,1859,25,1,10,2018,October,23,1,Tuesday,0
3,2019-08-17,7292,25,1,8,2019,August,17,5,Saturday,1
4,2019-01-06,4344,25,3,1,2019,January,6,6,Sunday,1

In [48]:
#extract week of the year
date['date_week']=date['date'].dt.isocalendar().week
date.sample(5)

,date,product_id,city_id,orders,date_month,date_year,date_month_name,date_day,date_dow,date_day_name,date_is_weekend,date_week
766,2018-07-13,3454,14,8,7,2018,July,13,4,Friday,0,28
708,2019-06-05,5004,25,5,6,2019,June,5,2,Wednesday,0,23
637,2019-02-15,957,22,4,2,2019,February,15,4,Friday,0,7
875,2018-11-01,4495,28,1,11,2018,November,1,3,Thursday,0,44
677,2019-03-04,1503,21,1,3,2019,March,4,0,Monday,0,10

In [ ]:
#quarter
date['quarter']=date['date'].dt.quarter
date.sample(5)

,date,product_id,city_id,orders,date_month,date_year,date_month_name,date_day,date_dow,date_day_name,date_is_weekend,date_week,quarter
29,2019-02-20,172,0,7,2,2019,February,20,2,Wednesday,0,8,1
789,2019-02-02,3741,25,4,2,2019,February,2,5,Saturday,1,5,1
668,2019-11-01,6937,13,38,11,2019,November,1,4,Friday,0,44,4
801,2018-12-17,630,10,12,12,2018,December,17,0,Monday,0,51,4
253,2018-10-13,3793,22,32,10,2018,October,13,5,Saturday,1,41,4

In [51]:
#semester
date['semester']=np.where(date['quarter'].isin([1,2]),1,2)
date.sample(5)

,date,product_id,city_id,orders,date_month,date_year,date_month_name,date_day,date_dow,date_day_name,date_is_weekend,date_week,quarter,semester
583,2019-05-17,2589,20,2,5,2019,May,17,4,Friday,0,20,2,1
480,2019-02-06,3835,9,2,2,2019,February,6,2,Wednesday,0,6,1,1
313,2018-12-29,5118,13,125,12,2018,December,29,5,Saturday,1,52,4,2
912,2019-08-05,7140,18,37,8,2019,August,5,0,Monday,0,32,3,2
919,2019-06-01,6386,2,1,6,2019,June,1,5,Saturday,1,22,2,1

Extract Time elapsed between dates

In [52]:
import datetime
today=datetime.datetime.today()
today

datetime.datetime(2025, 2, 15, 20, 19, 16, 568626)

In [53]:
today-date['date']

0     1894 days 20:19:16.568626
1     2376 days 20:19:16.568626
2     2307 days 20:19:16.568626
3     2009 days 20:19:16.568626
4     2232 days 20:19:16.568626
                 ...
995   2322 days 20:19:16.568626
996   2263 days 20:19:16.568626
997   2111 days 20:19:16.568626
998   2176 days 20:19:16.568626
999   1950 days 20:19:16.568626
Name: date, Length: 1000, dtype: timedelta64[ns]

In [54]:
(today-date['date']).dt.days

0      1894
1      2376
2      2307
3      2009
4      2232
       ...
995    2322
996    2263
997    2111
998    2176
999    1950
Name: date, Length: 1000, dtype: int64

In [62]:
months_passed = ((today.year - date['date'].dt.year) * 12) + (today.month - date['date'].dt.month)

# Show the result
months_passed

0      62
1      78
2      76
3      66
4      73
       ..
995    76
996    74
997    69
998    71
999    64
Name: date, Length: 1000, dtype: int32

In [63]:
time

                    date                                                msg
0    2013-12-15 00:50:00                           ищу на сегодня мужика 37
1    2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2    2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3    2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4    2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше
..                   ...                                                ...
995  2012-03-16 00:50:00     ПАРЕНЬ СДЕЛАЕТ  МАССАЖ ЖЕНЩИНАМ -066-877-32-44
996  2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
997  2012-10-15 23:37:00  Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...
998  2012-06-21 23:34:00  7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14
999  2014-06-19 23:25:00          Парень поласкает девушке...  т.0662035584

[1000 rows x 2 columns]

In [64]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [66]:
time['date']=pd.to_datetime(time['date'])
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [72]:
time['hour']=time['date'].dt.hour
time['min']=time['date'].dt.minute
time['second']=time['date'].dt.second
time.sample(5)

,date,msg,hour,min,second
334,2013-04-01 01:12:00,жду тебя любимая,1,12,0
460,2013-11-06 01:14:00,Катя с др тебя от всего класса,1,14,0
568,2014-06-25 22:55:00,ИЩЮ ДЕВУШКУ С Ч\\Ю П.25Л 0993041437,22,55,0
988,2013-08-22 23:10:00,ЛЕВА ПРИВ ДОМ ВСЕ ХОРОШ ЗАВТР БУД ПЕРЕД ОТ ВЛА...,23,10,0
12,2013-06-05 01:05:00,.эксперементаторше. 0678676246,1,5,0

Time Diffrence

In [75]:
#in seconds
(today-time['date'])/np.timedelta64(1,'s')

0      3.525825e+08
1      3.408363e+08
2      3.828242e+08
3      3.225164e+08
4      3.568220e+08
           ...
995    4.077921e+08
996    3.491322e+08
997    3.893069e+08
998    3.993294e+08
999    3.364308e+08
Name: date, Length: 1000, dtype: float64